### ISSUE TITLE
Improve error messages on unknown mods

### ISSUE THREAD

**Issue by jspaezp** [jspaezp/ms2ml#5]
Example:

```
>>> foo = Peptide.from_sequence("AAINQK[+28.0]LIETGER")
>>> foo.mod_to_
foo.mod_to_count(   foo.mod_to_onehot(  foo.mod_to_vector(  
>>> foo.mod_to_vector()
2022-11-08 04:51:48.327 | DEBUG    | ms2ml.proforma_utils:resolve:70 - Resolving +28
2022-11-08 04:51:48.328 | DEBUG    | ms2ml.proforma_utils:solver:54 - Initializing UnimodResolver
2022-11-08 04:51:48.926 | DEBUG    | ms2ml.proforma_utils:resolve:72 - Resolved to {'composition': Composition({'H': 4, 'C': 2}), 'name': 'Delta:H(4)C(2)', 'id': 255, 'mass': 28.0313, 'provider': 'unimod'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpaezpae/micromamba/envs/ef_data/lib/python3.9/site-packages/ms2ml/peptide.py", line 486, in mod_to_vector
    vector.append(order_mapping[x])
KeyError: '[U:255]'
```

**Comment by jspaezp** [comment]
https://github.com/jspaezp/ms2ml/commit/8256d4fa3baa9862d9baa36c7670cb847c3eed03
